### ISSUE TITLE
Project optimization in terms of speed of operation

### ISSUE THREAD

**Issue by dam-orzel** [Feature-Checker/Feature-Checker#14]

**Comment by mras2303** [comment]
Hope it is ready on TEST env. Will be refactored PROD code.

@AzotoN1 could you check it on TEST env?

Currently link is [https://dev-release.com](here)

**Comment by mras2303** [comment]
- [ ] http should redirect to https
- [ ] https working well
- [ ] speed page is optimize
- [ ] size of prod code is in optimize range

**Comment by mras2303** [comment]
Link to TEST environment [https://dev-release.com:70](url)
