### ISSUE TITLE
Getting logos for tools

### ISSUE THREAD

**Issue by mras2303** [Feature-Checker/Feature-Checker#20]
Github API doesn't provide logo assets. Should we add it manually or just find another way to fetch them. To discuss.

**Comment by dam-orzel** [comment]
We can't add them manually, at least to the landing page, because the technology list will be generated and sorted based on how the technology is downloaded, evaluated, etc.

**Comment by mras2303** [comment]
I mean adding logo manually to database

**Comment by dam-orzel** [comment]
There is such an option, but there can be many such technologies and I do not know if we can add these logos ourselves

**Comment by mras2303** [comment]
This is what we need to discuss about with Łukasz

**Comment by dam-orzel** [comment]
Ok
