### ISSUE TITLE
Add tool - any event should be fired

### ISSUE THREAD

**Issue by mras2303** [Feature-Checker/Feature-Checker#35]
Event should be fired to start searching image in the network (delay is mandatory to avoid API requests)

**Comment by dam-orzel** [comment]
is the button enough?

**Comment by mras2303** [comment]
Better will be some kind of "onblur" to get results from endpoint after finish of typing repoName

**Comment by dam-orzel** [comment]
Something like this?
https://codepen.io/seanhak/pen/ezzwWz

**Comment by mras2303** [comment]
Yes, but we need to fire it in delay because of call Google API

**Comment by dam-orzel** [comment]
Done,

It's simple becouse we don't have any logic there, try type "facebook/react".

**Comment by mras2303** [comment]
```javascript
const axios = require("axios");

const isUrlValid = async(url) => {
    // add logic to extract just two "words" between first slash
    url += 'https://github.com/'
    try {
        await axios.get(url);
        console.log(`Valid URL: ${url}`);
        return true;
    } catch (err) {
        console.log(`Not a valid URL: ${url}`);
        return false;
    }
}

isUrlValid("facebook/react");
isUrlValid("react");
isUrlValid("123sad/sa/d/sad/");
```

Could you add that validation before searching link validation?
