### ISSUE TITLE
Ununique key in elements of list

### ISSUE THREAD

**Issue by mras2303** [Feature-Checker/Feature-Checker#47]
File: client\src\views\Templates\Development\Frontend.vue
Line: 16

**Comment by dam-orzel** [comment]
![image](https://user-images.githubusercontent.com/42767180/71340414-038a5000-2557-11ea-8180-15446dbbdfd4.png)

Warning exist

**Comment by mras2303** [comment]
Key need to be changed to Id from DB in the future

**Comment by dam-orzel** [comment]
Yup, for now, close
